name: CI/CD

on:
  pull_request:
    paths:
      - .github/workflows/CICD.yml
      - tower-of-delusion/**
  push:
    branches: main
    paths:
      - .github/workflows/CICD.yml
      - tower-of-delusion/**

permissions:
  id-token: write
  
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.*
        
    - name: Install dotnet-sort-refs global tool
      run: dotnet tool install --global dotnet-sort-refs

    - name: Build reason
      run: echo ${{github.ref}} and ${{github.event_name}} by ${{github.triggering_actor}}
      
    - name: Build and Test
      env:
          DOCKER_USR: ${{ vars.DOCKER_USR }}
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      run: dotnet run --project ./tower-of-delusion/src/TowerOfDelusion.Build -c Release -- build
      
    - name: 'Az CLI login'
      uses: azure/login@v1
      if: github.ref == 'refs/heads/main'
      with:
        client-id: ${{ vars.ARM_CLIENT_ID }}
        tenant-id: ${{ vars.ARM_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        
    - name: Push image
      if: github.ref == 'refs/heads/main'
      run: |
        az acr login --name pier8
        dotnet run --project ./tower-of-delusion/src/TowerOfDelusion.Build -c Release -- push-image

  deploy-production:
    name: Deploy to production
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get ShortSHA
        run: echo "CI_COMMIT_SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.*
          
      - name: Pulumi up
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: ritasker/TowerOfDelusion.Pulumi/production
          work-dir: tower-of-delusion/src/TowerOfDelusion.Pulumi
          config-map: "{tower-of-delusion:ImageTag: $CI_COMMIT_SHORT_SHA}"
        env:
          ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}