name: cloud-resources\ci

on:
  push:
    branches: main
    paths: 
      - .github/workflows/cloud-resources-ci.yml
      - src/cloud-resources/**
      
defaults:
  run:
    working-directory: src/cloud-resources

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.*
        
    - name: Build reason
      run: echo ${{github.ref}} and ${{github.event_name}}

    - name: Build and test
      run: dotnet build -c Release CloudResources.slnf